create table CLIENT_MASTER



(CLIENT_NO VARCHAR(6) PRIMARY KEY NOT NULL,

NAME VARCHAR(20) NOT NULL,

ADDRESS1 VARCHAR(30),

ADDRESS2 VARCHAR(30),

CITY VARCHAR(15),

PINCODE NUMERIC(8),

STATE VARCHAR(15),

BALDUE NUMERIC(10,2));

INSERT INTO CLIENT_MASTER(CLIENT_NO,NAME,ADDRESS1,ADDRESS2,CITY,PINCODE,STATE,BALDUE)VALUES('C00001','IVAN','UDAYAM','PERINGAVE','MALAPPURAM',673633,'KERALA', 12335),

('C00003','SREDHA', 'PANGINIKOT','AYIKARAPADI','MALAPPURAM',673637,'KERALA',122333),('C00002','KRISHNA', 'PANG','RAMANATTUKARA','KOZHIKODE',673657,'KERALA',12333),

('C00004','SREDHA KRISHNA V', 'AAVE','RAMANATTUKARA','KOZHIKODE',674637,'KERALA',12333);

INSERT INTO CLIENT_MASTER(CLIENT_NO,NAME,ADDRESS1,ADDRESS2,CITY,PINCODE,STATE,BALDUE)VALUES('C00005','IVAN BAYROSS','MUMBAI','MUMBAI','MUMBAI',400054,'MAHARASHTRA',15000);

SELECT * FROM CLIENT_MASTER

CREATE TABLE PRODUCT_MASTER(

PRODUCTNO VARCHAR(6) PRIMARY KEY NOT NULL,

DESCRITION VARCHAR(15) NOT NULL,

PROFITPERC NUMERIC(4,2) NOT NULL,

UNITMEASURE VARCHAR(10) NOT NULL,

QTYONHAND NUMERIC(8) NOT NULL,

REORDERLEVEL NUMERIC(8) NOT NULL,

SELLPRICE NUMERIC(8,2) CHECK (SELLPRICE!=0) NOT NULL,

COSTPRICE NUMERIC (8,2)CHECK(COSTPRICE!=0) NOT NULL);

INSERT INTO PRODUCT_MASTER (PRODUCTNO,DESCRITION,PROFITPERC,UNITMEASURE,QTYONHAND,REORDERLEVEL,SELLPRICE,COSTPRICE)VALUES

('P00001','T_SHIRTS',5,'PIECE',200,50,250,350),('P00002','KURTI',6,'PIECE',300,30,200,360),

('P00003','SHIRTS',5,'PIECE',200,50,250,300),('P00004','SAREE',5,'PIECE',100,60,250,350)

SELECT * FROM PRODUCT_MASTER

CREATE TABLE SALESMAN_MASTER(

SALESMANNO VARCHAR(6) PRIMARY KEY NOT NULL,

SALESMANNAME VARCHAR(20) NOT NULL,

ADDRESS1 VARCHAR(30) NOT NULL,

ADDRESS2 VARCHAR(30) NOT NULL,

CITY VARCHAR(20),

PINCODE NUMERIC(8),

STATE VARCHAR(20),

SALMAT NUMERIC(8,2) CHECK(SALMAT!=0) NOT NULL,

TGTTOGET NUMERIC(6,2) NOT NULL,

YTDSALES NUMERIC(6,2) NOT NULL,

REMARKS VARCHAR(60));

INSERT INTO SALESMAN_MASTER(SALESMANNO,SALESMANNAME,ADDRESS1,ADDRESS2,CITY,PINCODE,STATE,SALMAT,TGTTOGET,YTDSALES,REMARKS)VALUES

('S00001','AMAN','A/14','WORIL','MUMBAI', 400002,'MAHARASHTRA',3000,100,50,'GOOD'),

('S00002','ARAVIND','304','CITY','MALAPPURAM',330022,'KERALA',2000,300,30,'NICE'),

('S00003','AAMI','B/14','CITY','KOZHIKODE',373633,'KERALA',1000,200,40,'GOOD');

SELECT * FROM SALESMAN_MASTER;

create table SALES_ORDER

(ORDERNO VARCHAR(6) PRIMARY KEY,

CLIENTNO VARCHAR(6) FOREIGN KEY REFERENCES CLIENT_MASTER(CLIENT_NO) ,

ORDERDATE DATE,DELYADDR VARCHAR(25),

SALESMANNO VARCHAR(6) FOREIGN KEY REFERENCES SALESMAN_MASTER(SALESMANNO) ,

DELYTYPE CHAR(1)CHECK(DELYTYPE='P' OR DELYTYPE='F') ,

BILLEDYN CHAR(1)CHECK(BILLEDYN='Y'OR BILLEDYN='N') ,

DELYDATE DATE,

ORDERSTATUS VARCHAR(10)CHECK (ORDERSTATUS='IN PROCESS'OR ORDERSTATUS='FULLFILLED'OR ORDERSTATUS='BACKORDER'OR ORDERSTATUS='CANCELLED' ) );

INSERT INTO SALES_ORDER(ORDERNO,ORDERDATE,ClientNo,DelyType,BilledYn,SalesmanNo,DelyDate,OrderStatus)values('O19001','12-june-02',

'C00001','F','N','S00001','20-july-02','In Process'),('O19002','13-january-03','C00002','f','N','S00001','20-july-02','In Process'),

('O19003','12-june-04','C00001','F','N','S00002','20-july-02','In Process');

SELECT * FROM SALES_ORDER;

create table SALES_ORDER_DETAILS(ORDERNO VARCHAR(6) FOREIGN KEY REFERENCES SALES_ORDER(ORDERNO) ,

PRODUCTNO VARCHAR(6) FOREIGN KEY REFERENCES PRODUCT_MASTER(PRODUCTNO),

QTYORDERED NUMERIC(8),

QTYDISP NUMERIC(2),

PRODUCTRATE NUMERIC(10,2 ))

INSERT INTO SALES_ORDER_DETAILS(OrderNo,PRODUCTNO,QtyOrdered,QtyDisp,ProductRate)values('O19001','P00001',4,4,525);

SELECT * FROM SALES_ORDER_DETAILS

SELECT NAME FROM CLIENT_MASTER;

SELECT * FROM CLIENT_MASTER WHERE CITY='MUMBAI'

SELECT * FROM PRODUCT_MASTER WHERE SELLPRICE BETWEEN 2000 AND 5000;

SELECT NAME,CITY,STATE FROM CLIENT_MASTER WHERE STATE!='MAHARASHTRA';

SELECT * FROM CLIENT_MASTER WHERE CLIENT_NO='C00001'OR CLIENT_NO ='C00002';

UPDATE PRODUCT_MASTER

SET SELLPRICE=1150

WHERE SELLPRICE=200;

--SELECT * FROM PRODUCT_MASTER

DELETE FROM CLIENT_MASTER WHERE CLIENT_NO='C00005';

--SELECT * FROM CLIENT_MASTER

SELECT * FROM CLIENT_MASTER WHERE CITY LIKE '_O%';

SELECT COUNT(*) FROM PRODUCT_MASTER WHERE SELLPRICE>=1000

--10]]]]]]]]]]

ALTER TABLE CLIENT_MASTER

ADD PHONE_N0 VARCHAR(20);

--SELECT *FROM CLIENT_MASTER

ALTER TABLE CLIENT_MASTER

DROP COLUMN PINCODE

ALTER TABLE CLIENT_MASTER

ALTER COLUMN NAME VARCHAR(60)

--JOINS

SELECT * FROM CLIENT_MASTER

JOIN SALES_ORDER ON SALES_ORDER.CLIENTNO=CLIENT_MASTER.CLIENT_NO

WHERE CLIENT_MASTER.NAME='IVAN'

--2

SELECT * FROM SALES_ORDER_DETAILS

JOIN SALES_ORDER ON SALES_ORDER.ORDERNO=SALES_ORDER_DETAILS.ORDERNO

WHERE DELYDATE ='2002-07-20';

--3

select * from SALES_ORDER_DETAILS

join PRODUCT_MASTER ON PRODUCT_MASTER.PRODUCTNO = SALES_ORDER_DETAILS.QTYORD

